### PR TITLE
Add ptrdname search option to PtrRecord objects

### PR DESCRIPTION
**Pull request by chrisschroeder92**
I was having timeout issues searching by ipv4addr.  I've noticed in my environment, searching by ptrdname is much faster.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
Why is the build failing?

**Comment by bondar-pavel** [comment]
Looks good to me

**Comment by acjohnson** [comment]
Will this get rolled into a future release soon?

**Comment by bondar-pavel** [comment]
@johnbelamaric I guess I have access rights to release a new version with that patch.
Is it ok if I'll do that?

**Comment by johnbelamaric** [comment]
Sure, thanks Pavel! Hope you're enjoying your new gig :)

**Comment by bondar-pavel** [comment]
@johnbelamaric Great! Will release new version later today.
It looks like Infoblox made me addicted to opensource, so just can't stop contributing :)

**Comment by bondar-pavel** [comment]
@acjohnson This fix is available with 0.4.8 release:
https://pypi.python.org/pypi/infoblox-client/0.4.8

**Pull request merged**
