### PR TITLE
Add allowed_object_types field for EA Definition

### PR DESCRIPTION
**Pull request by yuewko**
Added support for 'allowed_object_types' attribute for Extensible
Attribute Definition.

### CODE REVIEW

**Comment by bondar-pavel** [comment]
I don't see this field in wapidoc on my NIOS VM:
https://172.23.25.175/wapidoc/objects/extensibleattributedef.html?highlight=extensibleattributedef

Is it added only in some latest wapi versions?
If yes then we can't add it to _return_fields because request will fail on older wapi versions.
However even in this case adding it to _fields is ok.

**Comment by bondar-pavel** [comment]
I have checked that even current version fails on request with wapi 2.0, most of these fields are added at later version.
To fix it we can leave  '_return_fields = []'  blank.
Nios will generate default list of fields for particular wapi verision.

**Comment by bondar-pavel** [comment]
'_return_fields = []' usually returns only a few fields.
I am thinking about merging it as is a creating an issue to come up with some solution for _return_fields issue for different wapi versions.

**Comment by yuewko** [comment]
For the purpose of the create_ea_defs tool, leaving _return_fields as [] would work - since the code only uses the 'name' field. I added all the fields because they are useful for diagnostics reason.

For now, I'll just set it to [].

**Comment by yuewko** [comment]
Actually, it would appear that, with WAPI version 2.0, it doesn't even support creation of EA Definitions.  IOW, it would require 2.2 for the tool to work at all.

I propose, therefore, to leave it as it is.

**Comment by bondar-pavel** [comment]
Ok, let's merge it as is and I'll create issue with _return_fields for all objects at once

**Pull request merged**
