### PR TITLE
Add Extensible Attribute Definition support 

### PR DESCRIPTION
**Pull request by yuewko**
…Manager.

Please bump version after it's merged.

### CODE REVIEW

**Comment by bondar-pavel** [comment]
Code looks ok, but commit message has to be fixed.
Please follow this guide while writing commit messages:
https://wiki.openstack.org/wiki/GitCommitMessages

Next formatting rules should be always followed:
- Provide a brief description of the change in the first line.
- Insert a single blank line after the first line.
- Provide a detailed description of the change in the following lines, breaking paragraphs where needed.
- The first line should be limited to 50 characters and should not end with a period.
- Subsequent lines should be wrapped at 72 characters.

So current commit message violates rule 'first line shorter than 50 characters'.

You can use 'commit --amend' to fix commit message.

**Comment by bondar-pavel** [comment]
'Add Extensible Attribute Definition support'
probably will be a good one for the first line.

**Comment by yuewko** [comment]
Please bump version after merge.

**Comment by bondar-pavel** [comment]
Looks good now. Thanks for fixing everything:)

**Pull request merged**
