### PR TITLE
[NIOS-84390] Client should throw error, when serching with non-searchable fields

### PR DESCRIPTION
**Pull request by sarya-infoblox**
# Issue/Feature description

* Invalid result while searching with Non-searchable fields

# How it was fixed/implemented

* Added functionality to check if the field is present in searchable fields else will raise an exception.

### CODE REVIEW

**Review by ranjishmp — APPROVED** [review]

**Review by achernevskii — CHANGES_REQUESTED** [review]
Can you cover these changes with unit, or e2e tests?

**Comment by sarya-infoblox** [comment]
Hi Aleksei,

All the test cases are working fine.

**Review by achernevskii — APPROVED** [review]

**Review by achernevskii — COMMENTED** [review]
@sarya-infoblox, @ranjishmp 

Client will return different errors in case of calling `get_object`, and `InfobloxObject.search` with non-searchable parameters. Is it expected?

**Comment by sarya-infoblox** [comment]
@achernevskii, yes I suppose it is expected as there are multiple calls for which 'get_object' and 'InfobloxObject.search' are returning different error messages.

**Pull request merged**
