### PR TITLE
Added EADefinitionManager

### PR DESCRIPTION
**Pull request by yuewko**

### CODE REVIEW

**Comment by bondar-pavel** [comment]
I believe that these new methods could be added into object_manager rather than creating new class for that. But that is discussable point, so let me know your thoughts about it.
Object_manager already has connector and all other methods in object manager is doing similar things as EADefinitionManager do, just for another objects.

And we for sure need UT for these new methods to at least do not decrease code coverage for infoblox-client. And current version decreases it significantly.
> Merging #7 into master will decrease coverage by -1.40% as of 85690da

**Comment by yuewko** [comment]
Agreed on all points!!

**Comment by bondar-pavel** [comment]
Thanks Ko!
Code and tests looks good, just need to squash all commits (4 of them) into one:
http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
After that I will merge this pull request.

**Comment by bondar-pavel** [comment]
replaced by #8

**Pull request closed without merging**
