### PR TITLE
Added 'is_created' attribute in InfobloxObjects.

### PR DESCRIPTION
**Pull request by adsri**
This attribute can be used to check if object is created
or pre-exist in NIOS.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
I agree. I *think* in Python you can return the two values, and when called in a single-value context, it will just return the first one.

**Comment by ishantt** [comment]
Yes @yuewko I agree that is_created should not be part of the object as it is not the property of the object.

If we return multi value also from the the create() then we will have to put checks all over the code to check if it is created on not. This means more unit tests and more maintenance.

What I can think of is to set a EA called "request_id " for all the NIOS objects like what we do for tenant_id. As rollback is for a request we can easily check if the object is created in that request or is being reused from earlier create request. 

During creation of object we can set 'request_id' EA and in the rollback decorator method we can check if the object in the rollback list has the same request_id as the current context request_id. If it is same then delete that object . If not then ignore it.

@johnbelamaric  @yuewko Let me know your inputs about this.

**Comment by yuewko** [comment]
@ishantt , I recognize that you would need to change code where `create() `is called to receive the additional return value. 

Presumably you can just ignore the additional `is_created` return value as appropriate. Obviously, where `create()` is NOT called with `check_if_exists` explicitly set to `False`, you can safely ignore the `is_created` return value. I did a quick check of number of places that is affected - it's quite a few but I don't think it's prohibitive. However....

@johnbelamaric , my main concern is that the change would not be backward compatible. Unfortunately, python is not golang - existing code that calls `create()` would be returned a tuple with the two return values :-(.  We 'could' make the current `create()` a wrapper of a new `create_return_is_create()` (please don't use this name) method.

**Comment by johnbelamaric** [comment]
Ok, for backward compatibility, let's create two separate calls. Something like `create_check_exists` that returns the two values, then the existing create call just calls that but returns only the first. The new call can be used explicitly where needed.

**Comment by yuewko** [comment]
@johnbelamaric , thanks for your input!! Agree 100%.

**Comment by ishantt** [comment]
@yuewko I think you missed my point. What I am trying to say is we do not need to do this change at all. Infact we do not need to change the infoblox-client and only make in the networking-infoblox project. @adsri has put up the patch implementing what I am trying to convey above. (https://review.openstack.org/#/c/462675 )

Akash has tested this and it works and this approach looks much cleaner to me.

**Comment by yuewko** [comment]
@ishantt , here's why I believe we should follow @johnbelamaric 's recommendation:
- The fact that the `create()` method does not currently return the `is_created` flag is clearly a missing feature that is obviously useful.
- Adding the `create_check_exists()` method is a much cleaner way to implement the fix.

What do you think?

**Comment by ishantt** [comment]
@yuewko @johnbelamaric My only concern with returning two values is that each create call will lead to too many **if else** in the networking-infoblox code. 
For eg : https://review.openstack.org/#/c/462675/1/networking_infoblox/neutron/common/dns.py 
and for each such if we will have to write two unit test cases, one to check if it is created newly and one to test if it already exists.

**Comment by yuewko** [comment]
@ishantt , @johnbelamaric clearly recommended **not** to change the `create()` method, but to **add** one called `create_check_exists()`. 
If we do that, there's probably less than 5 lines change in Infoblox-client. And the change to networking-Infoblox (https://review.openstack.org/#/c/462675/2) will only need to be 10% of what it is now.

**Comment by johnbelamaric** [comment]
In places where we don't care about that value, we use the `create` method. In places we do care, we use the `create_check_exists`.

**Comment by adsri** [comment]
Raised: https://github.com/infobloxopen/infoblox-client/pull/162 for the fix.

**Pull request closed without merging**
